In [139]:
import numpy as np

In [40]:
class Solution:
    def removeElement(self, nums, val):
        i=0
        j=len(nums)-1

        while i<=j:
            numi = nums[i]
            numj = nums[j]
            print(numi,numj, '----------------')
            if numi==val:
                # print('current number', numi)
                if numj!=val:
                    # print('heya')
                    nums[i],nums[j] = nums[j],nums[i]
                    i+=1
                    j-=1
                else:
                    print('heya')
                    j-=1
            else:
                i+=1
            print(nums)
        print(i,j)
        return max(i,j)

In [41]:
nums = [3,2,2,3]
val = 3
Solution().removeElement(nums, val)

3 3 ----------------
heya
[3, 2, 2, 3]
3 2 ----------------
[2, 2, 3, 3]
2 2 ----------------
[2, 2, 3, 3]
2 1


2

In [42]:
(5+5)**3

1000

250

In [179]:
import numpy as np

# Generate a random 5x5 adjacency matrix for an undirected graph
num_vertices = 5
matrix = np.random.randint(0, 2, size=(num_vertices, num_vertices))
A = np.triu(matrix, 1) + np.triu(matrix, 1).T

A = A+np.eye(5)
A

array([[1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1.]])

In [182]:
A[0] = A[0]*0
A

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1.]])

In [183]:
(A@A.T)**3

array([[  0.,   0.,   0.,   0.,   0.],
       [  0., 125.,  27.,  64.,  27.],
       [  0.,  27.,  27.,  27.,   1.],
       [  0.,  64.,  27.,  64.,   8.],
       [  0.,  27.,   1.,   8.,  27.]])