In [139]:
import numpy as np

In [198]:
class Solution:
    def validPath(self, n, edges, source, destination):
        A = np.zeros((n,n))
        for u,v in edges:
            A[u,v] = 1
            A[v,u] = 1

        R = (A@A.T)**n
        print(R)
        return bool(R[source,destination])
        

In [199]:
len([[0,4]])

1

In [201]:
n = 5
edges = [[0,4]]
source = 0
destination = 4

Solution().validPath(n, edges, source, destination)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


False

In [195]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [179]:
import numpy as np

# Generate a random 5x5 adjacency matrix for an undirected graph
num_vertices = 5
matrix = np.random.randint(0, 2, size=(num_vertices, num_vertices))
A = np.triu(matrix, 1) + np.triu(matrix, 1).T

A = A+np.eye(5)
A

array([[1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1.]])

In [182]:
A[0] = A[0]*0
A

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1.]])

In [183]:
(A@A.T)**3

array([[  0.,   0.,   0.,   0.,   0.],
       [  0., 125.,  27.,  64.,  27.],
       [  0.,  27.,  27.,  27.,   1.],
       [  0.,  64.,  27.,  64.,   8.],
       [  0.,  27.,   1.,   8.,  27.]])